# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainwid.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWid(object):
    def setupUi(self, MainWid):
        MainWid.setObjectName("MainWid")
        MainWid.resize(972, 564)
        self.centralwidget = QtWidgets.QWidget(MainWid)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ShowCtrlBarPlaylistBgWidget = QtWidgets.QWidget(self.centralwidget)
        self.ShowCtrlBarPlaylistBgWidget.setObjectName("ShowCtrlBarPlaylistBgWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.ShowCtrlBarPlaylistBgWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.CtrlBarWid = CtrlBar(self.ShowCtrlBarPlaylistBgWidget)
        self.CtrlBarWid.setMinimumSize(QtCore.QSize(0, 60))
        self.CtrlBarWid.setMaximumSize(QtCore.QSize(16777215, 60))
        self.CtrlBarWid.setObjectName("CtrlBarWid")
        self.gridLayout.addWidget(self.CtrlBarWid, 1, 0, 1, 1)
        self.ShowWid = Show(self.ShowCtrlBarPlaylistBgWidget)
        self.ShowWid.setMinimumSize(QtCore.QSize(100, 100))
        self.ShowWid.setObjectName("ShowWid")
        self.gridLayout.addWidget(self.ShowWid, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.ShowCtrlBarPlaylistBgWidget, 0, 0, 1, 1)
        MainWid.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWid)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 26))
        self.menubar.setObjectName("menubar")
        MainWid.setMenuBar(self.menubar)
        self.PlayList = QtWidgets.QDockWidget(MainWid)
        self.PlayList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PlayList.setAutoFillBackground(False)
        self.PlayList.setObjectName("PlayList")
        self.PlaylistContents = QtWidgets.QWidget()
        self.PlaylistContents.setStyleSheet("")
        self.PlaylistContents.setObjectName("PlaylistContents")
        self.PlayList.setWidget(self.PlaylistContents)
        MainWid.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.PlayList)
        self.statusbar = QtWidgets.QStatusBar(MainWid)
        self.statusbar.setObjectName("statusbar")
        MainWid.setStatusBar(self.statusbar)
        self.TitleWid = QtWidgets.QDockWidget(MainWid)
        self.TitleWid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TitleWid.setObjectName("TitleWid")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.TitleWid.setWidget(self.dockWidgetContents)
        MainWid.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.TitleWid)

        self.retranslateUi(MainWid)
        QtCore.QMetaObject.connectSlotsByName(MainWid)

    def retranslateUi(self, MainWid):
        _translate = QtCore.QCoreApplication.translate
        MainWid.setWindowTitle(_translate("MainWid", "MainWindow"))
from ctrlbar import CtrlBar
from show import Show
