# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_playlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Playlist(object):
    def setupUi(self, Playlist):
        Playlist.setObjectName("Playlist")
        Playlist.resize(110, 549)
        self.gridLayout = QtWidgets.QGridLayout(Playlist)
        self.gridLayout.setContentsMargins(0, 1, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.List = QtWidgets.QListWidget(Playlist)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        self.List.setFont(font)
        self.List.setFocusPolicy(QtCore.Qt.NoFocus)
        self.List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.List.setObjectName("List")
        item = QtWidgets.QListWidgetItem()
        self.List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.List.addItem(item)
        self.gridLayout.addWidget(self.List, 0, 0, 1, 1)

        self.retranslateUi(Playlist)
        QtCore.QMetaObject.connectSlotsByName(Playlist)

    def retranslateUi(self, Playlist):
        _translate = QtCore.QCoreApplication.translate
        Playlist.setWindowTitle(_translate("Playlist", "Form"))
        __sortingEnabled = self.List.isSortingEnabled()
        self.List.setSortingEnabled(False)
        item = self.List.item(0)
        item.setText(_translate("Playlist", "testlist0"))
        item = self.List.item(1)
        item.setText(_translate("Playlist", "testlist1"))
        item = self.List.item(2)
        item.setText(_translate("Playlist", "testlist2"))
        self.List.setSortingEnabled(__sortingEnabled)
