# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_title.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Title(object):
    def setupUi(self, Title):
        Title.setObjectName("Title")
        Title.resize(826, 50)
        Title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gridLayout = QtWidgets.QGridLayout(Title)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MovieNameLab = QtWidgets.QLabel(Title)
        self.MovieNameLab.setText("")
        self.MovieNameLab.setObjectName("MovieNameLab")
        self.gridLayout.addWidget(self.MovieNameLab, 0, 1, 1, 1)
        self.MaxBtn = QtWidgets.QPushButton(Title)
        self.MaxBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.MaxBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.MaxBtn.setText("")
        self.MaxBtn.setObjectName("MaxBtn")
        self.gridLayout.addWidget(self.MaxBtn, 0, 3, 1, 1)
        self.CloseBtn = QtWidgets.QPushButton(Title)
        self.CloseBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.CloseBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.CloseBtn.setText("")
        self.CloseBtn.setObjectName("CloseBtn")
        self.gridLayout.addWidget(self.CloseBtn, 0, 5, 1, 1)
        self.FullScreenBtn = QtWidgets.QPushButton(Title)
        self.FullScreenBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.FullScreenBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.FullScreenBtn.setText("")
        self.FullScreenBtn.setObjectName("FullScreenBtn")
        self.gridLayout.addWidget(self.FullScreenBtn, 0, 4, 1, 1)
        self.MinBtn = QtWidgets.QPushButton(Title)
        self.MinBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.MinBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.MinBtn.setText("")
        self.MinBtn.setObjectName("MinBtn")
        self.gridLayout.addWidget(self.MinBtn, 0, 2, 1, 1)
        self.MenuBtn = QtWidgets.QPushButton(Title)
        self.MenuBtn.setMinimumSize(QtCore.QSize(130, 0))
        self.MenuBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(18)
        self.MenuBtn.setFont(font)
        self.MenuBtn.setObjectName("MenuBtn")
        self.gridLayout.addWidget(self.MenuBtn, 0, 0, 1, 1)

        self.retranslateUi(Title)
        QtCore.QMetaObject.connectSlotsByName(Title)

    def retranslateUi(self, Title):
        _translate = QtCore.QCoreApplication.translate
        Title.setWindowTitle(_translate("Title", "Form"))
        self.MenuBtn.setText(_translate("Title", "Demo"))
